"""Request ID middleware tests."""

import uuid

from fastapi.testclient import TestClient


def test_generates_request_id_when_absent(client: TestClient) -> None:
    response = client.get("/health")

    request_id = response.headers.get("x-request-id")
    assert request_id is not None
    # Must be a valid UUID when generated by the middleware.
    uuid.UUID(request_id)


def test_echoes_inbound_request_id(client: TestClient) -> None:
    inbound = "test-correlation-123"
    response = client.get("/health", headers={"X-Request-ID": inbound})

    assert response.headers.get("x-request-id") == inbound
